const actionTypes = {
    ADD_DOG_REQUESTED: 'ADD_DOG_REQUESTED',
    ADD_DOG_SUCCEEDED: 'ADD_DOG_SUCCEEDED',
    EDIT_DOG_REQUESTED: 'EDIT_DOG_REQUESTED',
    EDIT_DOG_SUCCEEDED: 'EDIT_DOG_SUCCEEDED',
    DELETE_DOG_REQUESTED: 'DELETE_DOG_REQUESTED',
    DELETE_DOG_SUCCEEDED: 'DELETE_DOG_SUCCEEDED',
};

export { actionTypes };
