export default {
    dogName: 'Dog Name',
    breed: 'Breed',
    description: 'Description',
    noDogsFound: 'No dogs found',
    dogs: 'Dogs',
    addDog: 'Add Dog',
    addNewDog: 'Add New Dog',
    dogBreed: 'Dog Breed',
    dogColor: 'Dog Color',
    pleaseEnterDogName: 'Please enter dog name',
    pleaseEnterDogBreed: 'Please enter dog breed',
    pleaseEnterDogColor: 'Please enter dog color',
    pleaseEnterDescription: 'Please enter description',
    dogAddedSuccessfully: 'Dog added successfully',
    deleteDog: 'Delete Dog',
    cancel: 'Cancel',
    delete: 'Delete',
    areYouSureToDeleteDog: 'Are you sure you want to delete the dog?',
    update: 'Update',
    remove: 'Remove',
    edit: 'Edit',
    editDog: 'Edit dog details',
    dogUpdatedSuccessfully: 'Dog updated successfully',
    dogDeletedSuccessfully: 'Dog deleted succesfully',
    done: 'Done'
};
